<html>
<head>
<title>...</title>
<style type="text/css">
table {
margin: 8px;
}

body{
    background-color: #181a1b;;
}

b {
font-family: Arial, Helvetica, sans-serif;
font-size: 30px;
color: #FFF;
}

p{
    font-family: Arial, Helvetica, sans-serif;
    font-size: 20px;
    color: #FFF;
}

h2{
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
    color: #FFF;
}

h3{
    font-family: Arial, Helvetica, sans-serif;
    font-size: 20px;
    color: cornflowerblue;
}

td {
font-family: Arial, Helvetica, sans-serif;
font-size: .7em;
border: 1px solid #DDD;
}

h1{
    text-align: center;
    color: #FFF;
}

img{
    float: left;
    margin-right: 20px;
}

</style>
</head>